export const CommonStr = {
  useraleart: "Please enter your UserNameh",
  namealeart: "Please enter your first name",
  lastnamealeart: "Last name is required.",
  emailaleart: "please Enter Email Id",
  mobilealeart: "Mobile number is mandatory and it must be of length 10",
  bdatealeart: "Select the date of birth.",
  citystatealeart: "City or State not selected.",
  pincodealeart: "Choose Pincode",
  ratealeart: "Give Your Feedback",
  usererr: "Please enter a valid userName",
  nameerr: "Enter Name",
  lastnameerr: "Enter Last NAme",
  emailerr: "Please enter a valid email address",
  cityerr: "Enter City NAme",
  mobileerr: "Invalid Phone number and it must be 10 Digits",
  pincodeerr: "Invalid PinCode",
  erruploadimg: "Error Uploading Image : ",
  closedialog: "Close Dialog",
  astric: "*",
  textname: "Enter Name",
  name: "Name",
  username: "User Name",
  textusername: "Enter User Name",
  textlastname: "Enter Last Name",
  lastname: "Last Name",
  textemail: "Enter Email Id",
  mail: "Email Id",
  mobile: "Phone No",
  textmobile: "Enter Phone No.",
  birthdate: "Choose Birth Date",
  textcity: "Enter City",
  city: "City",
  pincode: "Pincode",
  textpincode: "Enter Pincode",
  sortname: "Acending & Decending Name",
  sortrate: "Acending & Decending Rating",
  sortdate: "Acending & Decending Date",
};

export const CommonSize = {
  f12: {
    fontSize: 40,
  },
};
